name: Hello World Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite la ejecución manual del workflow

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Hola Mundo"
