name: Cargar contenedor de docker

on:
  push:
    branches:
      - main  # Ejecutar este workflow en cada push a la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Objetivo: añadir la clave SSH al agente que se conectará al servidor.
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_PEM }}

    # Objetivo: Verificar que la conexión se realizó exitosamente.
    - name: Verify SSH connection
      env:
        EC2_IP: ${{ secrets.AWS_HOST }}
        EC2_USER: ${{ secrets.AWS_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP "echo 'Conexión exitosa a EC2'"

    # Objetivo: Acceder al contenedor Docker y replicar el repositorio en la carpeta "src".
    - name: Deploy to EC2 - DOCKER FOLDER
      env:
        EC2_IP: ${{ secrets.AWS_HOST }}
        EC2_USER: ${{ secrets.AWS_USER }}
        REPO_URL: ${{ secrets.HTTP_GIT }}  # URL del repositorio - es la dirección SSH o HTTP que usamos para el git clone
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << 'EOF'
          docker exec -it baa7da4f3ad2 /bin/bash -c "
          cd /app/src &&
          git clone $REPO_URL .
          "
        EOF