# utils/mappings.py

provincias = {
    "NACION": 1,
    "CIUDAD AUTONOMA DE BUENOS AIRES": 2,
    "C.AUTONOMA DE BS.AS": 2,
    "CABA": 2,
    "BUENOS AIRES": 6,
    "CATAMARCA": 10,
    "CORDOBA": 14,
    "CORRIENTES": 18,
    "CHACO": 22,
    "CHUBUT": 26,
    "ENTRE RIOS": 30,
    "FORMOSA": 34,
    "JUJUY": 38,
    "LA PAMPA": 42,
    "LA RIOJA": 46,
    "MENDOZA": 50,
    "MISIONES": 54,
    "NEUQUEN": 58,
    "RIO NEGRO": 62,
    "SALTA": 66,
    "SAN JUAN": 70,
    "SAN LUIS": 74,
    "SANTA CRUZ": 78,
    "SANTA FE": 82,
    "SANTIAGO DEL ESTERO": 86,
    "SGO.DEL ESTERO": 86,
    "TUCUMAN": 90,
    "TIERRA DEL FUEGO": 94,
    "T.DEL FUEGO": 94,
}

provinciass = {
            'Estado Nacional': 1,
            'Capital Federal': 2,
            'Buenos Aires': 6,
            'Catamarca': 10,
            'Chaco': 22,
            'Chubut': 26,
            'Córdoba': 14,
            'Corrientes': 18,
            'Entre Rios': 30,
            'Formosa': 34,
            'Jujuy': 38,
            'La Pampa': 42,
            'La Rioja': 46,
            'Mendoza': 50,
            'Misiones': 54,
            'Neuquén': 58,
            'Rio Negro': 62,
            'Salta': 66,
            'San Juan': 70,
            'San Luis': 74,
            'Santa Cruz': 78,
            'Santa Fe': 82,
            'Santiago del Estero': 86,
            'Tierra del Fuego': 94,
            'Tucuman': 90,
}

provincias_superm = [
    ['Total', 1, 1],
    ['Ciudad Autónoma de Buenos Aires', 2, 2],
    ['24 partidos del Gran Buenos Aires ', 6, 2],  # espacio al final necesario
    ['Resto de Buenos Aires', 6, 3],
    ['Catamarca', 10, 4],
    ['Chaco', 22, 5],
    ['Chubut', 26, 7],
    ['Córdoba', 14, 3],
    ['Corrientes', 18, 5],
    ['Entre Ríos', 30, 3],
    ['Formosa', 34, 5],
    ['Jujuy', 38, 4],
    ['La Pampa', 42, 3],
    ['La Rioja', 46, 4],
    ['Mendoza', 50, 6],
    ['Misiones', 54, 5],
    ['Neuquén', 58, 7],
    ['Río Negro', 62, 7],
    ['Salta', 66, 4],
    ['San Juan', 70, 6],
    ['San Luis', 74, 6],
    ['Santa Cruz', 78, 7],
    ['Santa Fe', 82, 3],
    ['Santiago del Estero', 86, 4],
    ['Tierra del Fuego', 94, 7],
    ['Tucumán', 90, 4],
]

categorias_nacion_sipa = {
    "Empleo asalariado en el sector privado": 2,
    "Empleo asalariado en el sector público": 3,
    "Empleo en casas particulares": 4,
    "Trabajo Independientes Autónomos": 5,
    "Trabajo Independientes Monotributo": 6,
    "Trabajo Independientes Monotributo Social": 7,
    "Total": 8,
}

aeropuertos = {
    'aeroparque': 'Aeroparque',
    'bahia_blanca': 'Bahía Blanca',
    'bariloche': 'Bariloche',
    'base_marambio': 'Base Marambio',
    'catamarca': 'Catamarca',
    'chapelco': 'Chapelco',
    'comod_rivadavia': 'Comod. Rivadavia',
    'concordia': 'Concordia',
    'cordoba': 'Córdoba',
    'corrientes': 'Corrientes',
    'el_calafate': 'El Calafate',
    'el_palomar': 'El Palomar',
    'esquel': 'Esquel',
    'ezeiza': 'Ezeiza',
    'formosa': 'Formosa',
    'general_pico': 'General Pico',
    'goya': 'Goya',
    'gualeguaychu': 'Gualeguaychú',
    'iguazu': 'Iguazú',
    'jujuy': 'Jujuy',
    'junin': 'Junín',
    'la_plata': 'La Plata',
    'la_rioja': 'La Rioja',
    'malargue': 'Malargüe',
    'mar_del_plata': 'Mar del Plata',
    'mendoza': 'Mendoza',
    'moreno': 'Moreno',
    'moron': 'Morón',
    'neuquen': 'Neuquén',
    'parana': 'Paraná',
    'paso_de_los_libres': 'Paso de los Libres',
    'posadas': 'Posadas',
    'puerto_madryn': 'Puerto Madryn',
    'reconquista': 'Reconquista',
    'resistencia': 'Resistencia',
    'rio_cuarto': 'Río Cuarto',
    'rio_gallegos': 'Río Gallegos',
    'rio_grande': 'Río Grande',
    'rosario': 'Rosario',
    'salta': 'Salta',
    'san_fernando': 'San Fernando',
    'san_juan': 'San Juan',
    'san_luis': 'San Luis',
    'san_rafael': 'San Rafael',
    'santa_fe': 'Santa Fe',
    'santa_rosa': 'Santa Rosa',
    'santa_rosa_de_conlara': 'Santa Rosa de Conlara',
    'santiago_del_estero': 'Santiago del Estero',
    'tandil': 'Tandil',
    'termas_rio_hondo': 'Termas Río Hondo',
    'trelew': 'Trelew',
    'tucuman': 'Tucumán',
    'ushuaia': 'Ushuaia',
    'viedma': 'Viedma',
    'villa_gesell': 'Villa Gesell',
    'villa_reynolds': 'Villa Reynolds',
    'otros': 'Otros'
}

meses_esp = {
    'Enero': '01', 'Febrero': '02', 'Marzo': '03', 'Abril': '04',
    'Mayo': '05', 'Junio': '06', 'Julio': '07', 'Agosto': '08',
    'Septiembre': '09', 'Octubre': '10', 'Noviembre': '11', 'Diciembre': '12'
}

meses_abbr = {
    'ene': '01', 'feb': '02', 'mar': '03', 'abr': '04', 'may': '05', 'jun': '06',
    'jul': '07', 'ago': '08', 'sep': '09', 'oct': '10', 'nov': '11', 'dic': '12'
}
