# utils/mappings.py

provincias = {
    "NACION": 1,
    "CIUDAD AUTONOMA DE BUENOS AIRES": 2,
    "CABA": 2,
    "BUENOS AIRES": 6,
    "CATAMARCA": 10,
    "CORDOBA": 14,
    "CORRIENTES": 18,
    "CHACO": 22,
    "CHUBUT": 26,
    "ENTRE RIOS": 30,
    "FORMOSA": 34,
    "JUJUY": 38,
    "LA PAMPA": 42,
    "LA RIOJA": 46,
    "MENDOZA": 50,
    "MISIONES": 54,
    "NEUQUEN": 58,
    "RIO NEGRO": 62,
    "SALTA": 66,
    "SAN JUAN": 70,
    "SAN LUIS": 74,
    "SANTA CRUZ": 78,
    "SANTA FE": 82,
    "SANTIAGO DEL ESTERO": 86,
    "TUCUMAN": 90,
    "TIERRA DEL FUEGO": 94,
}


categorias_nacion_sipa = {
    "Empleo asalariado en el sector privado": 2,
    "Empleo asalariado en el sector público": 3,
    "Empleo en casas particulares": 4,
    "Trabajo Independientes Autónomos": 5,
    "Trabajo Independientes Monotributo": 6,
    "Trabajo Independientes Monotributo Social": 7,
    "Total": 8,
}

aeropuertos = {
    'aeroparque': 'Aeroparque',
    'bahia_blanca': 'Bahía Blanca',
    'bariloche': 'Bariloche',
    'base_marambio': 'Base Marambio',
    'catamarca': 'Catamarca',
    'chapelco': 'Chapelco',
    'comod_rivadavia': 'Comod. Rivadavia',
    'concordia': 'Concordia',
    'cordoba': 'Córdoba',
    'corrientes': 'Corrientes',
    'el_calafate': 'El Calafate',
    'el_palomar': 'El Palomar',
    'esquel': 'Esquel',
    'ezeiza': 'Ezeiza',
    'formosa': 'Formosa',
    'general_pico': 'General Pico',
    'goya': 'Goya',
    'gualeguaychu': 'Gualeguaychú',
    'iguazu': 'Iguazú',
    'jujuy': 'Jujuy',
    'junin': 'Junín',
    'la_plata': 'La Plata',
    'la_rioja': 'La Rioja',
    'malargue': 'Malargüe',
    'mar_del_plata': 'Mar del Plata',
    'mendoza': 'Mendoza',
    'moreno': 'Moreno',
    'moron': 'Morón',
    'neuquen': 'Neuquén',
    'parana': 'Paraná',
    'paso_de_los_libres': 'Paso de los Libres',
    'posadas': 'Posadas',
    'puerto_madryn': 'Puerto Madryn',
    'reconquista': 'Reconquista',
    'resistencia': 'Resistencia',
    'rio_cuarto': 'Río Cuarto',
    'rio_gallegos': 'Río Gallegos',
    'rio_grande': 'Río Grande',
    'rosario': 'Rosario',
    'salta': 'Salta',
    'san_fernando': 'San Fernando',
    'san_juan': 'San Juan',
    'san_luis': 'San Luis',
    'san_rafael': 'San Rafael',
    'santa_fe': 'Santa Fe',
    'santa_rosa': 'Santa Rosa',
    'santa_rosa_de_conlara': 'Santa Rosa de Conlara',
    'santiago_del_estero': 'Santiago del Estero',
    'tandil': 'Tandil',
    'termas_rio_hondo': 'Termas Río Hondo',
    'trelew': 'Trelew',
    'tucuman': 'Tucumán',
    'ushuaia': 'Ushuaia',
    'viedma': 'Viedma',
    'villa_gesell': 'Villa Gesell',
    'villa_reynolds': 'Villa Reynolds',
    'otros': 'Otros'
}